import "./globals.css";
import AllProviders from "@/components/AllProviders";


export const metadata = {
  title: "Counsel Matrix",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
    >
      <body>
        <AllProviders>
          {children}
        </AllProviders>
      </body>
    </html>
  );
}
